archivo = open ("archivo.txt", "w")
archivo.write("Hola, boticas!\n")
archivo.write("¿Cómo están?\n")
archivo.close()
archivo = open("archivo.txt", "r")
contenido = archivo.read()
print("Contenido del archivo:")
print(contenido)
archivo.close()